const mockData = {
  count: 30,
  results: [
    { id: 1, firstName: 'David', lastName: 'Wallace' },
    { id: 2, firstName: 'Sonia', lastName: 'Ross' },
    { id: 3, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 4, firstName: 'David', lastName: 'Wallace' },
    { id: 5, firstName: 'Sonia', lastName: 'Ross' },
    { id: 6, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 7, firstName: 'David', lastName: 'Wallace' },
    { id: 8, firstName: 'Sonia', lastName: 'Ross' },
    { id: 9, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 10, firstName: 'David', lastName: 'Wallace' },
    { id: 11, firstName: 'Sonia', lastName: 'Ross' },
    { id: 12, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 13, firstName: 'David', lastName: 'Wallace' },
    { id: 14, firstName: 'Sonia', lastName: 'Ross' },
    { id: 15, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 16, firstName: 'David', lastName: 'Wallace' },
    { id: 17, firstName: 'Sonia', lastName: 'Ross' },
    { id: 18, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 19, firstName: 'David', lastName: 'Wallace' },
    { id: 20, firstName: 'Sonia', lastName: 'Ross' },
    { id: 21, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 22, firstName: 'David', lastName: 'Wallace' },
    { id: 23, firstName: 'Sonia', lastName: 'Ross' },
    { id: 24, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 25, firstName: 'David', lastName: 'Wallace' },
    { id: 26, firstName: 'Sonia', lastName: 'Ross' },
    { id: 27, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 28, firstName: 'David', lastName: 'Wallace' },
    { id: 29, firstName: 'Sonia', lastName: 'Ross' },
    { id: 30, firstName: 'Anthony', lastName: 'Thomson' },
  ],
}

export default mockData
