const data = {
  count: 30,
  results: [
    { id: 1, firstName: 'David', lastName: 'Wallace' },
    { id: 2, firstName: 'Sonia', lastName: 'Ross' },
    { id: 3, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 1, firstName: 'David', lastName: 'Wallace' },
    { id: 2, firstName: 'Sonia', lastName: 'Ross' },
    { id: 3, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 1, firstName: 'David', lastName: 'Wallace' },
    { id: 2, firstName: 'Sonia', lastName: 'Ross' },
    { id: 3, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 1, firstName: 'David', lastName: 'Wallace' },
    { id: 2, firstName: 'Sonia', lastName: 'Ross' },
    { id: 3, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 1, firstName: 'David', lastName: 'Wallace' },
    { id: 2, firstName: 'Sonia', lastName: 'Ross' },
    { id: 3, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 1, firstName: 'David', lastName: 'Wallace' },
    { id: 2, firstName: 'Sonia', lastName: 'Ross' },
    { id: 3, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 1, firstName: 'David', lastName: 'Wallace' },
    { id: 2, firstName: 'Sonia', lastName: 'Ross' },
    { id: 3, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 1, firstName: 'David', lastName: 'Wallace' },
    { id: 2, firstName: 'Sonia', lastName: 'Ross' },
    { id: 3, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 1, firstName: 'David', lastName: 'Wallace' },
    { id: 2, firstName: 'Sonia', lastName: 'Ross' },
    { id: 3, firstName: 'Anthony', lastName: 'Thomson' },
    { id: 1, firstName: 'David', lastName: 'Wallace' },
    { id: 2, firstName: 'Sonia', lastName: 'Ross' },
    { id: 3, firstName: 'Anthony', lastName: 'Thomson' },
  ],
}

export default data
